# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2025-12-10 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_event_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='ID события провайдера')),
                ('event_type', models.CharField(max_length=64, verbose_name='тип события')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('processed', 'Обработано'), ('error', 'Ошибка')], default='new', max_length=10, verbose_name='Статус обработки')),
                ('order_id', models.CharField(max_length=32, verbose_name='# заказа')),
                ('data', models.TextField(verbose_name='Данные')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-date'],
            },
        ),
    ]
